theme: jekyll-theme-architect

title: "@jlreymendez"
#description: "Thougths and portfolio"

github:
  is_project_page: false
  is_user_page: true

collections:
  - games
  - tools
  - prototypes

google_analytics: "UA-177785467-1"